---BASICS
---DDL COMMANDS
---CREATE TABLE, ALTER TABLE, DROP TABLE

-------------------------------------------module 2--------------------------------------------------------
create database feb22

use feb22

---1.Create a customer table which comprises of these columns – ‘customer_id’, ‘first_name’, ‘last_name’, ‘email’, ‘address’, ‘city’,’state’,’zip’
create table customer(customer_id int,first_name varchar(30),last_name varchar(30),email varchar(30),address varchar(15),city varchar(15),state varchar(30),zip int)

--2.Insert 5 new records into the table
insert into customer values(10,'Sanjay','satyapal','ss@gmail.com','7 kindgerland','pune','maharashtra',40112)
insert into customer values(11,'ravindra','desai','rd@gmail.com','45kindgerland','bangalore','karnataka',40112)
insert into customer values(13,'arvind','rao','ro@gmail.com','87kindgerland','pune','maharashtra',40112)
insert into customer values(21,'govind','patil','wa@gmail.com','78kindgerland','san jose','california',40112)
insert into customer values(22,'wanar','kapoor','gv@gmail.com','79kindgerland','chennai','tamilnadu',40112)

---3.Select only the ‘first_name’ & ‘last_name’ columns from the customer table

select first_name,last_name from customer

---4.Select those records where ‘first_name’ starts with “G” and city is ‘San Jose’

select * from customer where first_name like 'g%' and city like 'san jose'


----------------------------------case study -----------------------------------------------------------------------------------

select * from [dbo].[Fact]
select * from [dbo].[Location]
select * from [dbo].[Product]

---1) Display number of states present in location table?
select count(distinct state) as Count_of_states from Location

--2) How many products are of regular type ?
select count(product) as No_OF_REGULAR from product where type='Regular'

---3) How much spending has been done on marketing of product id 1
select sum(Marketing) as Total_marketing from Fact where productId=1

--4) What is the minimum sales of a product ?
select min(sales) as Minimum_sales from Fact

---5) Display max Cost of Good Sold(COGS). 
select Max(COGS) as Maximum_COGS from Fact

--6) Display the Details of the productid where product type is coffee
select * from Product where product_type='Coffee'

--7) Display the details where total_expenses is greater than 40. 
Select * from Fact where Total_Expenses >40 order by Total_Expenses

--8) What is the average sales in Area_Code 719 ?
Select Avg(Sales) as Average_Sales from Fact where Area_code=719

--9) Find out the total profit generated by Colorado state. 
select Sum(F.Profit) as Colorados_Profit from Fact F
inner join
Location L
On F.Area_code=L.Area_code
where State='Colorado'

--10) Display the average inventory for each product id.
Select avg(Inventory) as Average_Inventory from Fact group by ProductId

---11) Display state in a sequential order in a location table.
select distinct state from Location order by state desc
select distinct state from Location order by state asc

--12) Display the average budget margin where average budget margin should be greater than 100
select avg(Budget_Margin) as Average_Budget, ProductId from Fact 
Group by ProductId having Avg(Budget_Margin)>100

--13) What is the total sales done on date 2010-01-01
select sum(Sales) as Total_Sales from Fact where Date='2010-01-01'